In [3]:
import numpy as np
import time

In [6]:
#execute performances
size = 1_00_00
py_list = list(range(size))
start = time.time()
sq_list = [x**2 for x in py_list]
end = time.time()
print(f"python list time = {end - start} seconds")

#numpy arrays
np_arr = np.array(py_list)
start = time.time()
sq_array = np_arr**2
end = time.time()
print(f"numpy array time ={end - start} seconds")


python list time = 0.022095918655395508 seconds
numpy array time =0.002098560333251953 seconds


In [8]:
#memoey
import sys
print(f"python list size = {sys.getsizeof(py_list) * len(py_list)} bytes")
print(f"numpy array size = {np_arr.nbytes} bytes")

python list size = 800560000 bytes
numpy array size = 80000 bytes


In [20]:
#create - from lists
arr= np.array([1,2,3,4,5])
print(arr,type(arr))
arr2 = np.array([1,2,3,4,5,"prime"])
print(arr2,type(arr2))
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d, arr2d.shape)

[1 2 3 4 5] <class 'numpy.ndarray'>
['1' '2' '3' '4' '5' 'prime'] <class 'numpy.ndarray'>
[[1 2 3]
 [4 5 6]
 [7 8 9]] (3, 3)


In [32]:
#create
arr1 = np.zeros((2,3), dtype="int64") #prefill
print(arr1,arr1.shape)

arr2 = np.ones((2,3)) #prefill
print(arr2,arr2.shape)

arr3 = np.full((2,3), 100) #prefill with value
print(arr3,arr3.shape)

arr4 = np.eye(3) #identity matrix
print(arr4,arr4.shape)

arr5 = np.arange(1,11 ) #range element
print(arr5,arr5.shape)

arr6 = np.full((2,3), 100) #evenly spaced arrays
print(arr6,arr6.shape)

arr7 = np.linspace(1,100,4) #prefill
print(arr7,arr7.shape)

[[0 0 0]
 [0 0 0]] (2, 3)
[[1. 1. 1.]
 [1. 1. 1.]] (2, 3)
[[100 100 100]
 [100 100 100]] (2, 3)
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] (3, 3)
[ 1  2  3  4  5  6  7  8  9 10] (10,)
[[100 100 100]
 [100 100 100]] (2, 3)
[  1.  34.  67. 100.] (4,)


In [35]:
#properties
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])

print(arr.shape) #dimention
print(arr.size) #
print(arr.dtype)
print(arr.ndim)

float_arr = arr.astype(np.float64)
print(float_arr, float_arr.dtype)

(3, 3)
9
int64
2
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]] float64


In [40]:
#operation on array
arr = np.array([[1,2,3],[4,5,6]])
print(arr,arr.shape)
reshaped = arr.reshape((3,2))
print(reshaped,reshaped.shape)
flattened = arr.flatten() #2D to 1D
print (flattened,flattened.shape)

[[1 2 3]
 [4 5 6]] (2, 3)
[[1 2]
 [3 4]
 [5 6]] (3, 2)
[1 2 3 4 5 6] (6,)


In [45]:
#indexing
arr = np.array([1,2,3,4,5])
print(arr[0])
print(arr[4])

arr = np.array([[1,2,3],[4,5,6]])
print(arr[0][2])

#fancy indexing
arr = np.array([1,2,3,4,5])
idx = [0,1,3]
print(idx)

#boolean indexing
arr = np.array([1,2,3,4,5])

print(arr[arr>3])
print(arr[arr%2==0])

1
5
3
[0, 1, 3]
[4 5]
[2 4]


In [6]:
#slicing 
arr = np.array([1,2,3,4,5])
print(arr[1:4]) #[start,stop,step]
print(arr[1:])
print(arr[:4])
print(arr[::2])

[2 3 4]
[2 3 4 5]
[1 2 3 4]
[1 3 5]


In [9]:
#copy vs view
# nums= [1,2,3,4,5]
# sub_list = nums[1:3]
# print(sub_list)
# sub_list[0] = 200

# print(sub_list)
# print(nums)

arr=np.array([1,2,3,4,5])
sub_arr = nums[1:3].copy()
print(sub_arr)

sub_arr[0] = 200

print(sub_list)
print(nums)

[2, 3]
[200, 3]
[1, 2, 3, 4, 5]


In [11]:
#data types
arr = np.array([1,2,3,4,5,"prime"])

print(arr,arr.dtype)

['1' '2' '3' '4' '5' 'prime'] <U21
